---
title: "Class activity work"
---

## [Class activity 1 - 09/19](activity/act-1.pdf)

-   MSSC 5780 Presenters: [David Aguilera](activity/act-1_david.pptx), [Rachel Cutlan](activity/act-1_rachel.pptx)

-   MATH 4780 Questioners: Ethan Baierl, Patrick Campbell, Dylan Cardoza

## [Class activity 2 - 09/26](activity/act-2.pdf)

-   MSSC 5780 Presenters: [Timothy Goodwin](activity/act-2_timothy.pptx), Matt Jaeggin

-   MATH 4780 Questioners: Huangkun Chen, Davion Cook, Nicky Diaz

## [Class activity 3 - 10/10](activity/act-3.pdf)

-   MSSC 5780 Presenters: [Samantha Juedemann](activity/act-3_samantha.pptx), [Edward Liu](activity/act-3_edward.pdf)

-   MATH 4780 Questioners: Nathan Fisher, Alberto Gamez Gonzalez, Andrew Hiller

## [Class activity 4 - 10/24](activity/act-4.pdf)

-   MSSC 5780 Presenters: [Sylvester Mensah](activity/act-4_sylvester.pdf), [Navid Mohseni](https://rpubs.com/NavidMhs/Pitfalls)

-   MATH 4780 Questioners: Jake Konrad, Vanessa Lattas, Danny O'Shea

## [Class activity 5 - 11/14](activity/act-5.pdf)

-   MSSC 5780 Presenters: [Adam Reeson](activity/act-5_adam.pptx)

-   MATH 4780 Questioners: Kayley Reith, Donny Robbins, Ray Sun

## [Class activity 6 - 12/05](activity/act-6.pdf)

-   MSSC 5780 Presenters: Anesti Sotirovski, Tanjina Zaman

-   MATH 4780 Questioners: Violet Wang, T.J. James Whapham II, Serena Yang
