---
title: "Class activity description"
date-modified: last-modified
---

This class activity guideline was last updated on {{< meta date-modified >}}. The revised parts are colored in [blue]{.blue}.

## Date

There will be four in-class activities on **Thursdays on 2/15, 3/7, 4/11 and 5/2**.

## Format

On each class activity day, students are learning from each other through discussion.

-   The students will be randomly divided into **two** groups.

-   For each group, **two** students will be assigned as a discussion leader.

-   The assigned discussion leaders need to

    -   prepare the discussion materials
    -   present and teach the topic to the group
    -   prepare at least one learning activity for the topic (e.g. Q & A, little games, coding practice, etc)
    -   [**(optional)** nominate **one** to **three** students that are most engaged. Note that you two leaders **make one single decision and jointly nominate members**.]{.blue}

-   The group members need to

    -   learn the topic being discussed
    -   participate the learning activities designed by the leaders
    -   evaluate the leaders' performance
    -   [nominate the best leader]{.blue}
    
    
<!-- -   Each presenter should prepare *at least* **two non-Yes-No** questions for all participants to answer. -->

<!-- -   **Each of the [three assigned MATH 4780](activity-work.html)** students should ask either one or both presenters *at least one* **non-Yes-No** question. -->

-   The discussion is about **40 minutes** long, followed by a knowledge check.

## Discussion Materials

-   The leaders will get a discussion topic **as least one week** before the class activity.

-   No specific discussion or presentation style/format/materials are required. The leaders decide how they present their work, and lead the discussion.

-   The leaders should send their materials, PDF, slides for example, to Dr. Yu **before** the class begins on the class activity day.

-   Your discussion materials will be posted on [Activity work](activity-work.html) page.

## Knowledge Check

-   **Dr. Yu will ask questions about the topic being discussed.**

-   **Every student** needs to answer the questions that are worth 25 pts in total.


## Evaluation

There are 200 points for class participation in the final grade calculation. Every student will serve as a discussion leader one time, and a group member three times.

-   **Discussion leaders** (**80 pts**)

    -   Knowledge check performance (25 pts)
    
    The followings are evaluated by the group members [and Dr. Yu]{.blue}. 
    -   Quality of discussion materials (20 pts)
    -   Oral presentation and communication skills (20 pts)
    -   Learning activity design (10 pts)
    -   [Individual performance (5 pts)]{.blue}
        * [The nomineed best leader receives 5 pts. The other receives 3 pts.]{.blue}
        * [If there is tie, both receive 4 pts.]{.blue}
    
-   **Group members** (**40 pts**)

    -   Knowledge check performance (25 pts)
    -   Activity engagement (15 pts)
        * The most engaged nominees get 15 pts. Others get 12 pts.
        * [If there is no nomination, all memebers receive 14 pts.]{.blue}