---
title: "MSSC 6250 - Statistical Machine Learning"
tbl-colwidths: [5,10,30,5,5,5,5,5]
---

This page contains an outline of the topics, content, and assignments for the semester. Note that this schedule will be updated as the semester progresses, with all changes documented here.

::: column-screen-inset-right
| Week | Date        | Topic                                     |               To Do               |                                      Slides                                      |                     In-class Activities                      |             Homework             |   Project    |
|:-------:|---------|---------|:-------:|:---------:|:-------:|:-------:|:-------:|
|  1   | Tue, Jan 16 | Syllabus/Overview of Statistical Learning | [📖](/weeks/week-1.html "Week 1") | [🖥️](slides/01-syllabus.html "Syllabus")[🖥️](slides/02-overview.html "Overview") |                                                              |                                  |              |
|      | Thu, Jan 18 | Bias-variance tradeoff                    |                                   |                [🖥️](slides/03-bias-var.html "bias-var-tradeoff")                 |                                                              |                                  |              |
|  2   | Tue, Jan 23 | Linear Regression (review)                | [📖](/weeks/week-2.html "Week 2") |               [🖥️](slides/04-linear-reg.html "Linear regression")                |                                                              | [✍️](/hw/hw-1.html "Homework 1") |              |
|      | Thu, Jan 25 | Linear Regression (optimization)          |                                   |                                                                                  |                                                              |                                  |              |
|  3   | Tue, Jan 30 | Ridge Regression                          | [📖](/weeks/week-3.html "Week 3") |      [🖥️](slides/05-ridge-cv.html "Ridge regression and cross validation")       |                                                              |                                  |              |
|      | Thu, Feb 1  | Cross-Validation                          |                                   |                                                                                  |                                                              |                                  |              |
|  4   | Tue, Feb 6  | Feature Selection                         | [📖](/weeks/week-4.html "Week 4") |                   [🖥️](slides/06-lasso-vs.html "06-lasso-vs")                    |                                                              |                                  |              |
|      | Thu, Feb 8  | LASSO                                     |                                   |                                                                                  |                                                              | [✍️](/hw/hw-2.html "Homework 2") |              |
|  5   | Tue, Feb 13 | Splines                                   | [📖](/weeks/week-5.html "Week 5") |                    [🖥️](slides/07-splines.html "07-splines")                     |                                                              |                                  |              |
|      | Thu, Feb 15 | In-class Activity: Bootstrapping          |                                   |                                                                                  |    [✅](activity-work.html#class-activity-1 "Activity 1")    |                                  |              |
|  6   | Tue, Feb 20 | Bayesian Inference                        | [📖](/weeks/week-6.html "Week 6") |                      [🖥️](slides/08-bayes.html "08-bayes")                       |                                                              |                                  |              |
|      | Thu, Feb 22 | Bayesian Linear Regression                |                                   |                                                                                  |                                                              |                                  |              |
|  7   | Tue, Feb 27 | Binary Logistic Regression                | [📖](/weeks/week-7.html "Week 7") |                  [🖥️](slides/09-class-glm.html "09-class-glm")                   |                                                              |                                  |              |
|      | Thu, Feb 29 | Multinomial Logistic Regression           |                                   |                                                                                  |                                                              |                                  |              |
|  8   | Tue, Mar 5  | Discriminant Analysis                     |                📖                 |                                        🖥️                                        |                                                              |                                  |              |
|      | Thu, Mar 7  | Naive Bayes                               |                                   |                                                                                  | [✅](activity-work.html#class-activity-2 "class-activity-2") |                ✍️                |              |
|  9   | Tue, Mar 12 | ***NO CLASS: Spring break***              |                📖                 |                                        🖥️                                        |                                                              |                                  |              |
|      | Thu, Mar 14 | ***NO CLASS: Spring break***              |                                   |                                                                                  |                                                              |                                  |              |
|  10  | Tue, Mar 19 | K-Nearest Neighbors Regression            |                📖                 |                                        🖥️                                        |                                                              |                                  |              |
|      | Thu, Mar 21 | K-Nearest Neighbors Classification        |                                   |                                                                                  |                                                              |                                  |              |
|  11  | Tue, Mar 26 | Gaussian Process Regression               |                📖                 |                                        🖥️                                        |                                                              |                                  |              |
|      | Thu, Mar 28 | ***NO CLASS: Easter break***              |                                   |                                                                                  |                                                              |                                  |              |
|  12  | Tue, Apr 2  | Support Vector Machine                    |                📖                 |                                        🖥️                                        |                                                              |                                  |              |
|      | Thu, Apr 4  | Support Vector Machine                    |                                   |                                                                                  |                                                              |                ✍️                |              |
|  13  | Tue, Apr 9  | CART and Bagging                          |                📖                 |                                        🖥️                                        |                                                              |                                  | Guideline 📂 |
|      | Thu, Apr 11 | Random Forests and Boosting               |                                   |                                                                                  |                              ✅                              |                                  |              |
|  14  | Tue, Apr 16 | Principal Component Analysis              |                📖                 |                                        🖥️                                        |                                                              |                                  |              |
|      | Thu, Apr 18 | Recommender Systems                       |                                   |                                                                                  |                                                              |                                  |              |
|  15  | Tue, Apr 23 | K-Means Clustering                        |                📖                 |                                        🖥️                                        |                                                              |                                  |              |
|      | Thu, Apr 25 | Model-based Clustering                    |                                   |                                                                                  |                                                              |                                  | Proposal 📂  |
|  16  | Tue, Apr 30 | Neural Networks                           |                📖                 |                                        🖥️                                        |                                                              |                                  |              |
|  16  | Thu, May 2  | Deep Learning                             |                                   |                                                                                  |                              ✅                              |                                  |              |
:::

I reserve the right to make changes to the schedule.

```{r echo = FALSE}
knitr::knit_exit()
```

|      |      |       | Prepare | Slides | AE  |                                                    Labs                                                    | HW  | Exam | Project |
|-----|-----|-----|:---:|:---:|:---:|:---------------------------:|:---:|:---:|:---:|
| Week | Date | Topic |   📖    |   🖥️   | 📋  | [💻](https://sakai.duke.edu/samigo-app/servlet/Login?id=6fa7ebf3-01af-42a6-91ba-3e813d3901221641094171786) | ✍️  |  ✅  |   📂    |
