---
title: "Final Project Report Guidelines"
subtitle: "MSSC 6250 Machine Learning, Spring 2024"
date-modified: today
---

<!-- # Final Project Report Guidelines -->

## Deadline

- Please send me your **entire work** (written report, code, data, etc) by [**May 9, 2024 10 AM**]{.red}.

- *You receive 0 point if you miss the deadline.*


<!-- # Timeline and Things to Do -->

## Team up

-   You will be working as **a group of 3**. Each of you should send me *a list describing [your teammate's and your work duty and contribution]{.red} to your project before the deadline.* 

- *You lose 20 points if you don't meet the requirement or miss the deadline.*


## Project Writing

Your project can be in either of the following categories:

1. **Data Analysis (DA)** using one or more machine learning methods learned in class.

2. **Introduce a new machine learning model/method/algorithm (ML)** and compare it with the model/method/algorithms learned in class.



### Structure

If you choose to do **DA**, your report should include the following sections:

- **Introduction**: State why you think the questions you would like to answer are important or interesting, and why you think the method(s) you consider is an appropriate one to answer your questions.

- **Data**: Describe the selected data set. Perform a thorough exploratory data analysis.

- **Analysis**:
  + Explain the chosen model/method.
  + Show why the chosen model(s) is appropriate and better than others.
  + Answer your research questions by the analysis result.

- **Conclusion**: Restate your research question, and summarize how you learn from data to answer your questions. What is the contribution of this project? Discuss any limitation of your model/method, and how it could be improved for better inference or prediction results.
  
- **References/Bibliography**: Include a detailed list of references, including papers, books, websites, code, and any idea/work that is not produced by yourself.


If you choose to do **ML**, your report should include the following sections:

- **Introduction**: State why you choose to learn this new method. Provide an overview and little history of the method. Describe the intuition and idea of the method. What are the pros and cons of the method?

- **Model/Method**: Provide the mathematical expression of the model. Explain the model and its properties, and how we do the supervised or unsupervised learning with the model.

- **Simulation**: Do a simulation study, and compare the chosen method with other methods learned in class. Determine which method performs better under what conditions.

- **Discussion**: Based on the simulation results, discuss the advantages and disadvantages of the chosen method. Discuss any variants of the chosen method.

- **References/Bibliography**: Include a detailed list of references, including papers, books, websites, code, and any idea/work that is not produced by yourself.


### Format and Layout

-  Your written report is saved as [**one PDF**]{.red}.

- Your paper should have your **project title** and **your name** on the first page. Date, Abstract, Keywords are optional.

- Except the first title page, the margins should be no larger than **one inch.**

- Except the project title and section title, the font size is **12 pt**.

- Please use **1.5** or **double** line spacing.

- Your report, including everything, should have **at least 12 pages**, but **no more than 15 pages**.

- Your code should *NOT* be included in the paper.



### Code

- Your code should be able to **reproduce all the numerical results, outputs, tables, and figures shown in the report**, including the source of the raw data (where you find and load the data) if the project is about data analysis.



## Project Evaluation

Your project will be evaluated [**soley by Dr. Yu**]{.red} based on

- **Content**: 
  + The quality of research question and relevancy of data to those questions? For example, the relationship between human height and weight is a BAD question. An elementary-school height and weight data set is a BAD data set.
  + The quality of the chosen model. For example, one-way ANOVA is a BAD model.

- **Correctness, Completeness and Complexity**: 
  + Are machine learning methods carried out and explained correctly? 
  + Does project include rigorous analysis and models? Simple linear regression model lacks complexity.

- **Writing**: What is the quality of the machine learning model/method presentation, visualization, writing, and explanations.

- **Format**: Does the report follow the required format?

- **Creativity and Critical Thought**: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?

- **Reproducibility**: Can your code reproduce what you show in the paper?

- **Reference**: Do you cite others work properly?





<!-- Final words: Imagine you were in the last round of interview for a Data Scientist position of salary $150,000 offered by Google in Mountain View, CA. Your job is to generate a report that shows your ability to extract useful information from data. Cherish this opportunity! (True story: My PhD fellow at UC Santa Cruz entered the last round of the interview. Google asked her to generate a well-writen report in 24 hours!) -->




<!-- _**Note:** For APST master students, this course is used to evaluate and summarize your academic performance in the program that will be sent to Marquette graduate school._ -->

<!-- \textcolor{blue}{Dr. Yu reserves the right to make changes to the project guideline.} -->

<!-- One of you, please email me -->

<!--     (1) your team [*member list*]{.blue} -->
<!--     (2) your [*team name*]{.blue} -->

<!--     by [**Friday, 4/5 11:59 PM**]{.red}. -->

<!-- -   **Proposal**. Please send me a [**one-page PDF**]{.blue} describing what you are going to do for your project (no word limit) with your **project title** by [**Friday, 4/26 11:59 PM**]{.red}. -->

<!-- -   **Presentation**. You will be presenting your project on [**Thursday, 5/9 8 - 10 AM**]{.red}. -->

<!-- -   **Materials**. Please share your [**entire work**]{.blue} (slides, code, data, etc) by [**Thursday, 5/9 11:59 PM**]{.red}. -->

<!-- # Policy -->

<!-- ## **Team up!** -->

<!-- -   *Each one of you loses 3 points of your project grade if you don't meet the requirement or miss the deadline.* -->

<!-- -   You will be *randomly* assigned to a group if you do not belong to any group before the deadline. -->

<!-- ## **Proposal** -->

<!-- -   *Each one of you loses 3 points of your project grade if you don't meet the requirement or miss the deadline.* -->

<!-- -   Your proposal (in PDF) should include three parts: -->

<!--     -   Project title -->
<!--     -   The goal of your project. For example, what is the research question you'd like to answer? What are the machine learning models and algorithms you'd like to use? -->
<!--     -   The description of the data set (simulated or real) you use in your project. For example, where is the data set from, how large is the data, the variables you use for your project, etc. -->

<!-- -   Although it is risky, you can change your project topic after you submit your proposal if you decide to do something else. -->


<!-- ## **Presentation** -->

<!-- -   [Every student has to participate (in-person) in the final presentation in order to pass the course]{.red}. -->

<!-- -   Each group presentation should be between **19 and 20 minute** long, followed by **2 to 3 minute** Q&A. If your presentation is too short or too long, *every one of you loses 3 points* of your project grade. -->

<!-- -   Every group member has to present some part of the group work. **The one who does not present receives no point**. -->

<!-- -   Questions are encouraged during Q&A. Everyone is welcome to ask any questions about the projects. It helps everyone evaluate every group's project and presentation performance. See @sec-grading for grading policy. -->

<!-- -   **Each group is required to ask as least one question**. -->

<!--     -   The $k$-th group should ask at least one question to the $(k-1)$-th group in Q&A, $k = 2, \dots, 5$. -->
<!--     -   The 1st group will ask the last (5th) group questions about their project. -->

<!-- -   If you, as a group, don't ask a question when you should, *every one of you loses 3 points* of your project grade. -->

<!--     <!-- After the 1st group presentation, the 2nd group should ask at least one question in Q&A. After the 2nd group presentation, the 3rd group should at least ask one question in Q&A, and so on. The 1st group will ask the last (7th) group questions about their project.  -->

<!-- ## **Materials** -->

<!-- -   *Each one of you loses 3 points of your project grade if you don't meet the requirement or miss the deadline.* -->

<!-- -   You need to share your entire work, including slides, code, and data if applicable. -->

<!-- -   Your code should be able to **reproduce all the numerical results, outputs, tables, and figures shown in the slides**, including the source of the raw data (where you find and load the data) if your project involves data analysis. -->

<!-- # Project Content -->

<!-- Your project can be in either of the following categories: -->

<!-- 1. **Data Analysis (DA)** using one or more machine learning methods learned in class. -->

<!-- 2. **Introduce a new machine learning model/method/algorithm (ML)** and compare it with one or more model/method/algorithms learned in class. -->



<!-- ## Data Analysis -->

<!-- For your DA project, you need to -->

<!-- -   State why you think the questions you would like to answer are important or interesting, and why you think the method(s) you consider is an appropriate one to answer your questions. -->

<!-- -   Describe the selected data set. Perform a thorough exploratory data analysis. -->

<!-- - Explain the chosen model/method(s). -->

<!-- - Show why the chosen model(s) is appropriate and better than others. -->

<!-- - Answer your research questions by your analysis result. -->



<!-- ## New Machine Learning Model/Method/Algorithm -->

<!-- For your ML project, you need to -->

<!-- -   State why you choose to learn this new method. Provide an overview and little history of the method. Describe the intuition and idea of the method. What are the pros and cons of the method? -->

<!-- - Provide the mathematical expression of the model. Explain the model and its properties, and how we do the supervised or unsupervised learning with the model. -->

<!-- - Do a simulation study, and compare the chosen method with other methods learned in class. Determine which method performs better under what conditions. -->

<!-- - Based on the simulation results, discuss the advantages and disadvantages of the chosen method. Discuss any variants of the chosen method. -->




<!-- # Project Evaluation and Grading {#sec-grading} -->

<!-- -   Your project performance grade is *determined by your classmates and Dr. Yu*. -->

<!-- -   Table 1 shows your possible performance grade. For example, if your group finish in fourth place and you are elected as the best contributor, you receive 270 points. If your group finish in second place, and you are not the best contributor, you get 275 points. -->

<!-- -   Your project grade will be \quote{\texttt{project grade = performance grade - points lost due to violation of policy}} -->

<!-- ```{r, echo=FALSE} -->
<!-- # library(tidyverse) -->
<!-- first_ind <- c(300, 290, 280, 270, 260) -->
<!-- other_ind <- c(285, 275, 265, 255, 245) -->
<!-- # grade <- tibble(first_ind, other_ind) -->
<!-- # grade <- as.data.frame(grade) -->
<!-- grade <- data.frame(first_ind, other_ind) -->
<!-- rownames(grade) <- paste("Group Rank", 1:5) -->
<!-- colnames(grade) <- c("Best contributor", "Other members") -->
<!-- knitr::kable(grade, align = "c", caption = "Performance Grade Sheet", label = "tbl:grade") -->
<!-- ``` -->

<!-- ## Group Performance Evaluation -->

<!-- -   You will need to **evaluate all group projects except the one you work on**. -->

<!-- -   You evaluate group performance based on the rubric attached. Four evaluation criteria are considered: -->

<!--     -   **Project Content and Organization (8 pts)** -->
<!--     -   **Slides Quality (4 pts)** -->
<!--     -   **Oral Presentation Skill and Delivery (4 pts)** -->
<!--     -   **Interactions and Q&A (4 pts)** -->

<!-- -   The total points of a project presentation is **20** points. -->

<!-- -   Evaluation sheets will be provided on the presentation day. -->

<!-- -   How do you get the full points for each category? Check the requirements below. Note that for Content and Organization, data analysis and package projects have different requirements. -->

<!-- -   **Content and Organization (DA)** -->

<!--     -   Beautiful visualization helps find out relationship of variables and specification of models -->
<!--     -   All questions are answered accurately by the models -->
<!--     -   Discuss how and why the models are chosen -->
<!--     -   Detailed analysis -->
<!--     -   All ideas are presented in logical order -->

<!-- -   **Content and Organization (ML)** -->

<!--     -   Clearly descibe the introduced method. -->
<!--     -   Clear explanation on the pros and cons of the method. -->
<!--     -   Detailed comparison between the method and other methods via simulation study. -->
<!--     -   All ideas are presented in logical order -->

<!-- -   **Slides Quality** -->

<!--     -   Slides show code and output beautifully -->
<!--     -   Slides clearly aid the speaker in telling a coherent story -->
<!--     -   All tables and graphics are informative and related to the topic and make it easier to understand -->
<!--     -   Attractive design, layout, and neatness. -->

<!-- -   **Oral Presentation Skill** -->

<!--     -   Good volume and energy -->
<!--     -   Proper pace and diction -->
<!--     -   Avoidance of distracting gestures -->

<!-- -   **Interactions and Q&A** -->

<!--     -   Good eye contact with audience -->
<!--     -   Excellent listening skills -->
<!--     -   Answers audience questions with authority and accuracy -->

<!-- -   After you evaluate 4 group project presentations, you rank them from 1st to 4th based on their earned points. -->

<!-- -   **No two groups receive the same ranking**. If you give two or more groups some points, you still need to give them a different ranking, deciding which teams deserve a higher ranking according to your preference. -->

<!-- ## Individual Performance Evaluation -->

<!-- -   You choose **one** single person who you think contributes the most to your group project. -->

<!-- -   You *cannot* vote for yourself, and you can only vote for *one of your teammates*. -->

<!-- -   If you don't vote, you can't be the best contributor even if you obtain the most votes. The person with the second highest votes wins the best contribution reward. -->

<!-- -   If there is no one single person who gets the most votes, every team member remains the same grade. For example, if your group finish in third place, and there is no best contributor, all members receive 265 points (See Table 1). -->
