{
  "hash": "d882a54724e42b1830fb09621b4fb57b",
  "result": {
    "markdown": "---\ntitle: \"Simulation-based Inference 💻\"\nsubtitle: \"MATH 4780 / MSSC 5780 Regression Analysis\"\nauthor: \"Dr. Cheng-Han Yu <br> Department of Mathematical and Statistical Sciences <br> Marquette University\"\n# date: \"October 27 2023\"\n# macros: _macros.tex # import a list of TeX/LaTeX definitions\nformat: \n  revealjs:\n    code-line-numbers: false\n    #     - \"macros.tex\"\n    html-math-method:\n      method: mathjax\n      url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\n    # include-in-header:\n    highlight-style: arrow\n    code-block-bg: true\n    self-contained: false\n    slide-number: c/t    \n    incremental: false\n    width: 1800\n    height: 1000\n    margin: 0.05\n    logo: \"https://upload.wikimedia.org/wikipedia/commons/e/e8/Marquette_Golden_Eagles_logo.svg\"\n    footer: \"[math4780-f23.github.io/website](https://math4780-f23.github.io/website/)\"\n    theme: [\"simple\", \"slides.scss\"]\n    multiplex: true\n    code-link: true\n    fig-cap-location: bottom\n    fig-align: center\n    transition: none ## fade slide convex concave zoom\n    title-slide-attributes:\n      data-background-color: \"#447099\"\n      # data-background-image: images/paper-texture.jpg\n      # data-background-size: cover\n      # data-background-color: \"#698ED5\"\neditor: source\nexecute:\n  freeze: true\n  echo: false\n  purl: true\n---\n\n\n#  {visibility=\"hidden\"}\n\n\\def\\bx{\\mathbf{x}}\n\\def\\bg{\\mathbf{g}}\n\\def\\bw{\\mathbf{w}}\n\\def\\balpha{\\boldsymbol \\alpha}\n\\def\\bbeta{\\boldsymbol \\beta}\n\\def\\beps{\\boldsymbol \\epsilon}\n\\def\\bLambda{\\boldsymbol \\Lambda}\n\\def\\bX{\\mathbf{X}}\n\\def\\by{\\mathbf{y}}\n\\def\\bH{\\mathbf{H}}\n\\def\\bI{\\mathbf{I}}\n\\def\\bS{\\mathbf{S}}\n\\def\\bW{\\mathbf{W}}\n\\def\\T{\\text{T}}\n\\def\\cov{\\mathrm{Cov}}\n\\def\\cor{\\mathrm{Corr}}\n\\def\\var{\\mathrm{Var}}\n\\def\\E{\\mathrm{E}}\n\\def\\bmu{\\boldsymbol \\mu}\n\\DeclareMathOperator*{\\argmin}{arg\\,min}\n\\def\\Trace{\\text{Trace}}\n\n\n\n\n\n# Bootstrapping\n\n<h2> Idea of Bootstrapping </h2>\n<h2> Bootstrap Confidence Interval </h2>\n<h2> Bootstrap Confidence Interval for Linear Regression </h2>\n<h2> Randomization test for Linear Regression* </h2>\n\n::: notes\n- When CLT can no longer use applied, bootstraping is a way to quantify uncertainty. \n- It doesn't mean that we cannot use bootstraping when CLT is applicable. OK. \n- You can probably do bootstraping using your sample under any situation. \n- In other words, the method can be widely used in many situations, and in fact it is very popular in statistics and machine learning.\n- Ok let's see what it is.\n:::\n\n## Why Simulation-based Inference?\n\n- Let's go back to MATH 4720. How do we do interval estimation for population mean $\\mu$?\n\n. . .\n\n- $z$-interval when $\\sigma$ is known\n- Student's $t$-interval when $\\sigma$ is unknown\n\n::: question\nWhat are the assumptions in orderto use $z$ or $t$ intervals?\n:::\n\n. . .\n\n::: alert\n\nThe population is Gaussian. If not, the sample size is large enough so that the central limit theorem can be applied!\n\n:::\n\n\n. . .\n\n::: danger\nWe never answer this question in MATH 4720. What if the population is **not** Gaussian and the sample size $n$ is **small**, i.e., **CLT becomes powerless?**\n:::\n\n\n\n## Bootstrapping 👢\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n- The term **bootstrapping** comes from the phrase \n\n> *pulling oneself up by one’s bootstraps*\n\nwhich is a metaphor for accomplishing an impossible task without any outside help.\n\n- **Impossible task**: estimating a population parameter using data from *only the given single sample dataset, without CI formula and replicates of data*.\n\n:::\n\n\n\n::: {.column width=\"50%\"}\n\n::: small\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Source: http://dailywhiteboard.blogspot.com/2014/04/day-251-pull-yourself-up-by-your.html](./images/11-bootstrap/bootstrap.jpg){fig-align='center' width=90%}\n:::\n:::\n\n:::\n:::\n::::\n\n\n\n::: notes\n- **Note**: Notion of saying something about a population parameter using only information from an observed sample is the crux of statistical inference, it is not limited to bootstrapping.\n- The term **bootstrapping** comes from the phrase \"*pulling oneself up by one’s bootstraps*\", which is a metaphor for accomplishing an impossible task without any outside help.\n- In statistics scenario, it means that we are estimating a population parameter using data from *only the given single sample dataset, without CI formula and/or replicates of data*. \n- I call it **Impossible task**, but that's basically what statistics usually does.\n- So notion of saying something about a population parameter using only information from an observed sample is the crux of statistical inference, it is not limited to bootstrapping.\n:::\n\n\n\n## Rent in Manhattan\n::: question\nHow much do you think it costs to rent a typical 1 bedroom apartment in Manhattan?\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/11-bootstrap/apt.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n::: notes\n- Here is our example. How much do you think it costs to rent a typical 1 bedroom apartment in Manhattan NYC?\n- Well if you have no idea, at least we can say we are 100% confident that the average one-bedroom rent in Manhattan is between 0 to one million dollars.\n- it's not helping though.\n:::\n\n## Data\n- Consider 20 one-bedroom apartments that were randomly selected on Craigslist Manhattan from apartments listed as \"by owner\".\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmanhattan <- readr::read_csv(\"./data/manhattan.csv\")\nrange(manhattan)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1470 4195\n```\n:::\n\n```{.r .cell-code}\nglimpse(manhattan)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 20\nColumns: 1\n$ rent <dbl> 3850, 3800, 2350, 3200, 2150, 3267, 2495, 2349, 3950, 1795, 2145,…\n```\n:::\n:::\n\n\n\n::: notes\n- The minimum is 1470 and the rent can be as high as near $4200.\n:::\n\n\n## Parameter of Interest\n\n- Could focus on the median rent or mean rent depending on our research goal.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/11-bootstrap/unnamed-chunk-5-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n::: notes\n- We could focus on the median rent or mean rent depending on our research goal. Sometimes we are interested in other quantiles, not just median.\n\n<!-- - .question[ -->\n<!-- 👤 Is the mean or the median a better measure of typical rent in Manhattan? -->\n<!-- ] -->\n:::\n\n\n## Observed Sample vs. Bootstrap Population\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/11-bootstrap/rent-bootsamp.png){fig-align='center' width=90%}\n:::\n:::\n\n\n\nSample median = $2350 😱\n:::\n\n\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/11-bootstrap/rent-bootpop.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\nPopulation median = ❓\n:::\n::::\n\n**IDEA: _We think the sample is representative of the population, so create an artificial population by replicating the subjects from the observed ones._**\n\n\n\n::: notes\n- So based on the sample, the sample median rent is $2350.\n- The question is What's our BT population look like that we can sample from?\n- Well the idea is that we assume that there are probably more apartments like the ones in our observed sample in the population as well.\n- So here, basically the BT artificial population is made from our sample data, and the population is like so many replicates of our given sample.\n- Again, this is an artificial population, not the real population. If I had the real population, no inference  or estimation is needed. We know the truth. Right.\n:::\n\n## Bootstrap Population\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Source: Figure 12.1 of Introduction to Modern Statistics](./images/11-bootstrap/boot1prop1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n## Bootstrap Sampling\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Source: Figure 12.2 of Introduction to Modern Statistics](./images/11-bootstrap/boot1prop2.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n## Practical Bootstrap Sampling\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Source: Figure 12.4 of Introduction to Modern Statistics](./images/11-bootstrap/boot1prop4.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n::: notes\nTaking repeated resamples from the sample data is the same process as creating an\ninfinitely large estimate of the population. It is computationally more feasible to take resamples\ndirectly from the sample. Note that the resampling is now done with replacement (that is, the original\nsample does not ever change) so that the original sample and estimated hypothetical population are\nequivalent.\n::: \n\n\n## Bootstrapping Algorithm\n::: instructions\n- **[1] Take a bootstrap sample** \n  + [a random sample taken **with replacement** from the original sample, of the **same size** as the original sample.]{.blue}\n  \n- **[2] Calculate the bootstrap statistic** \n  + [a statistic such as mean, median, proportion, slope, etc. computed on the bootstrap samples.]{.blue}\n  \n- **[3] Repeat steps (1) and (2) many times to create a bootstrap distribution**\n  + [a distribution of bootstrap statistics.]{.blue}\n  \n- **[4] Calculate the bounds of the $(1-\\alpha)100\\%$ confidence interval**\n  + [the middle $(1-\\alpha)100\\%$ of the bootstrap distribution.]{.blue}\n  \n:::\n\n\n::: notes\n- So the BT scheme or algorithm is like this.\n- **[1] Take a bootstrap sample** - a random sample taken **with replacement** from the \noriginal sample, of the **same size** as the original sample. In this case it'll be 20.\n- **[2] Calculate the bootstrap statistic** - a statistic such as mean, median, \nproportion, slope, etc. computed on the bootstrap samples. Here we compute the median.\n- **[3] Repeat steps (1) and (2) many times to create a bootstrap distribution** - \na distribution of bootstrap statistics.\n- Finally we can make a histogram of those BT statistics, and **[4] Calculate the bounds of the $(1-\\alpha)100\\%$ confidence interval** as the middle $(1-\\alpha)100\\%$ of the bootstrap distribution.\n:::\n\n\n## [R Lab]{.pink} infer 📦 in [tidymodels](https://www.tidymodels.org/)\n:::: {.columns}\n\n::: {.column width=\"80%\"}\n- The objective of this package is to perform statistical inference using an expressive statistical grammar that coheres with the `tidyverse` framework.\n\n- <https://infer.netlify.app/>\n:::\n\n\n::: {.column width=\"20%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](https://raw.githubusercontent.com/rstudio/hex-stickers/main/SVG/infer.svg){fig-align='center' width=100%}\n:::\n:::\n\n:::\n::::\n\n. . .\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/11-bootstrap/ht-diagram.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n\n\n::: notes\n- So now we get the idea of BT. Let's see how to do it in R.\n- You can write your own code to implement the BT.\n- But here, we use the infer package to do so. It is one of the tidymodels package.\n- The infer package performs statistical inference using an expressive statistical grammar that coheres with the `tidyverse` design framework.\n- So in R we have `tidyverse` for data wrangling and visualization, and we have tidymodels for inference and modeling.\n- The tidymodels framework is pretty young. It's website was released last year. It is not very mature at this time, but I believe it will get more and more functionality and will be getting popular because its syntax is similar to tidyverse syntax.\n- The idea of using the infer package is basically shown in this workflow.\n- We start with specifying a hypothesis or response and predictors in general. In our case, we just specify the response variable of interest. Here our variable of interest is the rent.\n- And once the variable of interest is specified, we can start generating data and calculating the sample statistic we want. So in our case, we generate our data using BT, and we calculate the median. \n- And finally we can visualise the BT distribution and do the inference.\n:::\n\n## [R Lab]{.pink} Generate Bootstrap Samples of Medians\n\n+ `specify()` the variable of interest.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmanhattan |>\n    # specify the variable of interest\n    specify(response = rent) #<<\n```\n:::\n\n\n\n::: notes\n- All right, let's do it step by step.\n- First we specify our response variable using specify(response = rent)\n:::\n\n\n## [R Lab]{.pink} Generate Bootstrap Samples of Medians\n\n+ `specify()` the variable of interest.\n+ `generate()` a fixed number of bootstrap samples.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmanhattan |> \n    # specify the variable of interest\n    specify(response = rent) |>\n    # generate 15000 bootstrap samples\n    generate(reps = 15000, type = \"bootstrap\")  #<<\n```\n:::\n\n\n::: notes\n- And then we generate our BT samples using generate() function, reps 15000 times, and specify type = \"bootstrap\".\n:::\n\n\n\n## [R Lab]{.pink} Generate Bootstrap Samples of Medians\n+ `specify()` the variable of interest.\n+ `generate()` a fixed number of bootstrap samples.\n+ `calculate()` the bootstrapped statistic(s).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmanhattan |> \n    # specify the variable of interest\n    specify(response = rent) |>\n    # generate 15000 bootstrap samples\n    generate(reps = 15000, type = \"bootstrap\") |>\n    # calculate the median of each bootstrap sample\n    calculate(stat = \"median\")  #<<\n```\n:::\n\n\n\n::: notes\n- Once we collect or BT samples, we calculate the bootstrapped statistic(s) which is median using calculate() function. \n- The stat argument is \"median\"\n\n:::\n\n\n\n## [R Lab]{.pink} Generate Bootstrap Samples of Medians\n+ `specify()` the variable of interest.\n+ `generate()` a fixed number of bootstrap samples.\n+ `calculate()` the bootstrapped statistic(s).\n+ save bootstrapping distribution for analysis.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# save resulting bootstrap distribution\nboot_sample <- manhattan |> \n    # specify the variable of interest\n    specify(response = rent) |>  \n    # generate 15000 bootstrap samples\n    generate(reps = 15000, type = \"bootstrap\") |>  \n    # calculate the median of each bootstrap sample\n    calculate(stat = \"median\")\n```\n:::\n\n\n::: notes\n- Then we are done! We have the BT samples or distribution of median rent for analysis.\n- I just save it to the object called boot_sample.\n:::\n\n\n## [R Lab]{.pink} The bootstrap Sample\n\n::: question\n👤 How many observations are there in `boot_sample`? What does each observation represent?\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndplyr::glimpse(boot_sample)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 15,000\nColumns: 2\n$ replicate <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 1…\n$ stat      <dbl> 2350, 2350, 2350, 2350, 2350, 2350, 2350, 2550, 2350, 2350, …\n```\n:::\n:::\n\n\n- Each replicate median rent is calculated from a bootstrapped sample of size 20 from our original sample data.\n\n::: notes\n- So now you can see that we have 15000 median rents \n- Each replicate median rent is calculated from a bootstrapped sample of size 20 from our original sample data.\n:::\n\n\n## [R Lab]{.pink} Visualize the Bootstrap Distribution\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbt_dist <- ggplot(data = boot_sample, mapping = aes(x = stat)) +\n    geom_histogram(binwidth = 50) +\n    labs(title = \"Bootstrap distribution of medians\") + theme_bw()\nbt_dist\n```\n\n::: {.cell-output-display}\n![](./images/11-bootstrap/unnamed-chunk-18-1.png){fig-align='center' width=65%}\n:::\n:::\n\n\n::: notes\n- And this is the bootstrap distribution of medians that is generated purely by our sample data, and it is generated without using normal assumptions or CLT.\n:::\n\n\n\n## [R Lab]{.pink} Calculate the CI\n\n:::: {.columns}\n\n::: {.column width=\"40%\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbt_ci <- infer::get_ci(\n  boot_sample, level = .95)\nbt_ci\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 2\n  lower_ci upper_ci\n     <dbl>    <dbl>\n1    2162.     2875\n```\n:::\n:::\n\n:::\n\n\n::: {.column width=\"60%\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nbt_dist + geom_vline(xintercept = c(bt_ci$lower_ci, bt_ci$upper_ci), \n                     color = \"blue\") +\n    labs(subtitle = \"and 95% CI\") + theme_bw()\n```\n\n::: {.cell-output-display}\n![](./images/11-bootstrap/boot-ci-1.png){fig-align='center' width=100%}\n:::\n:::\n\n:::\n::::\n\n\n::: notes\nA 95% confidence interval is bounded by the middle 95% of the bootstrap distribution.\n:::\n\n\n# Bootstrapped CI for the Regression Slope\n\n## Quantify the Variability of the Slope\n\nIn simple linear regression, we\n\n- Bootstrap new samples $\\{x^b_j, y^b_j\\}_{j=1}^n$ from the original sample $\\{x_i, y_i\\}_{i=1}^n$.\n\n- Fit models to each of the bootstrapped samples and estimate the slope.\n\n- Use the distribution of the bootstrapped slopes to construct a confidence interval.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n## Bootstrap Sample 1\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/11-bootstrap/unnamed-chunk-22-1.png){fig-align='center' width=100%}\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/11-bootstrap/unnamed-chunk-23-1.png){fig-align='center' width=100%}\n:::\n:::\n\n:::\n:::\n\n## Bootstrap Sample 2\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/11-bootstrap/unnamed-chunk-24-1.png){fig-align='center' width=100%}\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/11-bootstrap/unnamed-chunk-25-1.png){fig-align='center' width=100%}\n:::\n:::\n\n:::\n:::\n\n## Bootstrap Sample 3\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/11-bootstrap/unnamed-chunk-26-1.png){fig-align='center' width=100%}\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/11-bootstrap/unnamed-chunk-27-1.png){fig-align='center' width=100%}\n:::\n:::\n\n:::\n:::\n\n## Bootstrap Sample 4\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/11-bootstrap/unnamed-chunk-28-1.png){fig-align='center' width=100%}\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/11-bootstrap/unnamed-chunk-29-1.png){fig-align='center' width=100%}\n:::\n:::\n\n:::\n:::\n\n## Bootstrap Sample 5\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/11-bootstrap/unnamed-chunk-30-1.png){fig-align='center' width=100%}\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/11-bootstrap/unnamed-chunk-31-1.png){fig-align='center' width=100%}\n:::\n:::\n\n:::\n:::\n\n. . .\n\n*so on and so forth...*\n\n## Bootstrap Samples 1 - 5\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/11-bootstrap/unnamed-chunk-32-1.png){fig-align='center' width=100%}\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/11-bootstrap/unnamed-chunk-33-1.png){fig-align='center' width=100%}\n:::\n:::\n\n:::\n:::\n\n## Bootstrap Samples 1 - 100\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/11-bootstrap/unnamed-chunk-35-1.png){fig-align='center' width=100%}\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/11-bootstrap/unnamed-chunk-36-1.png){fig-align='center' width=100%}\n:::\n:::\n\n:::\n:::\n\n## Slopes of bootstrap samples\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/11-bootstrap/unnamed-chunk-37-1.png){fig-align='center' width=100%}\n:::\n:::\n\n:::\n\n\n::: {.column width=\"50%\"}\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/11-bootstrap/unnamed-chunk-38-1.png){fig-align='center' width=100%}\n:::\n:::\n\n:::\n::::\n\n## Bootstrapped CI\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/11-bootstrap/unnamed-chunk-39-1.png){fig-align='center' width=100%}\n:::\n:::\n\n:::\n\n\n::: {.column width=\"50%\"}\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/11-bootstrap/unnamed-chunk-40-1.png){fig-align='center' width=100%}\n:::\n:::\n\n:::\n::::\n\n- A 95% confidence interval is bounded by the middle 95% of the bootstrap distribution.\n\n\n## [R Lab]{.pink} Fit Regression to Bootstrap Samples\n\n<!-- Take `100` bootstrap samples and fit models to each one: -->\n\n:::: {.columns}\n\n::: {.column width=\"55%\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(2023)\nboot_fits <- delivery_data |> \n  specify(time ~ cases) |> \n  generate(reps = 100, type = \"bootstrap\") |> \n  fit()\nboot_fits\n```\n:::\n\n\n:::\n\n\n\n::: {.column width=\"45%\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n```{.my_class600}\n# A tibble: 200 × 3\n# Groups:   replicate [100]\n  replicate term      estimate\n      <int> <chr>        <dbl>\n1         1 intercept    0.738\n2         1 cases        2.54 \n3         2 intercept    2.24 \n4         2 cases        2.33 \n5         3 intercept    4.16 \n6         3 cases        2.14 \n# ℹ 194 more rows\n```\n:::\n:::\n\n\n:::\n\n::::\n\n## [R Lab]{.pink} Bootstrap CI\n\n- **Percentile method**: Compute the 95% CI as the middle 95% of the bootstrap distribution:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nobserved_fit <- delivery_data |> \n  specify(time ~ cases) |> \n  fit()\nboot_fits |> get_ci(point_estimate = observed_fit, type = \"percentile\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 3\n  term      lower_ci upper_ci\n  <chr>        <dbl>    <dbl>\n1 cases        1.73      2.48\n2 intercept    0.485     6.81\n```\n:::\n:::\n\n\n. . .\n\n- **Standard error method**: Compute the 95% CI as the point estimate $\\pm$ \\~2 standard deviations of the bootstrap distribution:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nboot_fits |> get_ci(point_estimate = observed_fit, type = \"se\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 3\n  term      lower_ci upper_ci\n  <chr>        <dbl>    <dbl>\n1 cases        1.68      2.68\n2 intercept   -0.341     6.98\n```\n:::\n:::\n\n\n\n\n::: notes\nconfint(lm(time~cases, data = delivery_data))\n:::\n\n## [R Lab]{.pink} `car::Boot()`\n\n- `car::Boot()` is a simple interface to the `boot::boot()`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlm_fit <- lm(time ~ cases, data = delivery_data)\ncar_boot <- car::Boot(lm_fit, R = 100)\ncar::brief(car_boot$t)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n100 x 2 matrix (95 rows omitted)\n       (Intercept) cases\n  [1,]       1.159  2.40\n  [2,]       3.537  2.11\n  [3,]       0.961  2.35\n. . .                        \n [99,]       2.757  2.24\n[100,]       2.415  2.35\n```\n:::\n:::\n\n\n## [R Lab]{.pink} Histogram of Bootstrap Samples\n\n- BC$_a$ is the **accelerated bias-corrected percentile interval**.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhist(car_boot)\n```\n\n::: {.cell-output-display}\n![](./images/11-bootstrap/unnamed-chunk-46-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n## [R Lab]{.pink} `car::Confint()`\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncar::Confint(lm_fit, vcov. = vcov(car_boot))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nStandard errors computed by vcov(car_boot) \n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n            Estimate  2.5 % 97.5 %\n(Intercept)     3.32 -0.611   7.25\ncases           2.18  1.613   2.74\n```\n:::\n:::\n\n\n\n::: notes\n\ncheck boot::boot.ci\n\n:::\n\n\n## [R Lab]{.pink} `boot::boot()`\n\n- <https://stats.oarc.ucla.edu/r/faq/how-can-i-generate-bootstrap-statistics-in-r/> \n\n- ISL Lab 5.3.4",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}